//import the package that allows us to create server
const http = require('http');

//create a server
const server = http.createServer((req, res) => {

    console.log("log generated by index file from node app")
    res.write("welcome to NODE App");
    res.end();

});

//listen to port
server.listen(3000);

/*
Environment + Resources
-----------------------
OS (Linux)
NodeJS (Software / CLI)
Open Port (3000)
index.js

Command Terminal
----------------
node index.js

 */